1. File I/O

In [2]:
#lets see how to write or store in a file

#1.Create an Identity Matrix

In [3]:
import numpy as np

In [4]:
i2 = np.eye(2)

In [5]:
i2

array([[1., 0.],
       [0., 1.]])

In [6]:
np.savetxt('eye.txt', i2)

In [20]:
c,v = np.loadtxt('data.csv', delimiter =',', usecols=(6,7),unpack=True)

In [11]:
vwap = np.average(c, weights=v)
print('VWAP =',vwap)

VWAP = 350.5895493532009


In [12]:
print(c) #price

[336.1  339.32 345.03 344.32 343.44 346.5  351.88 355.2  358.16 354.54
 356.85 359.18 359.9  363.13 358.3  350.56 338.61 342.62 342.88 348.16
 353.21 349.31 352.12 359.56 360.   355.36 355.76 352.47 346.67 351.99]


In [13]:
print(v) #volume

[21144800. 13473000. 15236800.  9242600. 14064100. 11494200. 17322100.
 13608500. 17240800. 33162400. 13127500. 11086200. 10149000. 17184100.
 18949000. 29144500. 31162200. 23994700. 17853500. 13572000. 14395400.
 16290300. 21521000. 17885200. 16188000. 19504300. 12718000. 16192700.
 18138800. 16824200.]


In [14]:
#Lets use Mean function

In [15]:
print("Mean of Proice is = ",np.mean(c))

Mean of Proice is =  351.0376666666667


In [16]:
print("Mean of Volume is =",np.mean(v))

Mean of Volume is = 17395663.333333332


TIme Weighted Average

In [17]:
t = np.arange(len(c))

In [18]:
print("TWAP is = ",np.average(c, weights = t))

TWAP is =  352.4283218390804


Value Range

In [22]:
h,l = np.loadtxt('data.csv', delimiter =',', usecols=(4,5),unpack=True)

In [23]:
print("Highest of Stock price is = ", np.max(h))

Highest of Stock price is =  364.9


In [24]:
print("Lowest of Stock Price is =",np.max(l))

Lowest of Stock Price is = 360.5


In [25]:
#to Compute spread of an array (Range) by using ptp function


In [26]:
print('Spread of High Price is = ', np.ptp(h))

Spread of High Price is =  24.859999999999957


In [27]:
print('Spread of low Price is = ', np.ptp(l))

Spread of low Price is =  26.970000000000027


# Simple Statistics

In [28]:
#1. Calculate Median

In [29]:
print('Median of closing price is = ',np.median(c)) #to avoid effect of outlier

Median of closing price is =  352.055


In [30]:
#compare it with Average Closing price

print('Arithematic avg of Closing Price is =',np.mean(c))

Arithematic avg of Closing Price is = 351.0376666666667


In [31]:
#lets verify the median algorith for its correctness

sorted_close = np.msort(c)

In [32]:
sorted_close

array([336.1 , 338.61, 339.32, 342.62, 342.88, 343.44, 344.32, 345.03,
       346.5 , 346.67, 348.16, 349.31, 350.56, 351.88, 351.99, 352.12,
       352.47, 353.21, 354.54, 355.2 , 355.36, 355.76, 356.85, 358.16,
       358.3 , 359.18, 359.56, 359.9 , 360.  , 363.13])

In [42]:
N = len(c)
N
x =(N-1)/2
x

14.5

In [47]:
print("Middle Value is = ",sorted_close[15])

Middle Value is =  352.12


In [54]:
#Variance -  how does the stock price vary

In [55]:
print('Variance = ',np.var(c))

Variance =  50.126517888888884


In [59]:
print("Variance by def = ", np.mean((c - c.mean())**2)) #verification

Variance by def =  50.126517888888884


Calculating Stock returns by using diff and log functions

In [60]:
returns = np.diff(c)/c[:-1] #we are performing differenctiation of c array

In [61]:
returns

array([ 0.00958048,  0.01682777, -0.00205779, -0.00255576,  0.00890985,
        0.0155267 ,  0.00943503,  0.00833333, -0.01010721,  0.00651548,
        0.00652935,  0.00200457,  0.00897472, -0.01330102, -0.02160201,
       -0.03408832,  0.01184253,  0.00075886,  0.01539897,  0.01450483,
       -0.01104159,  0.00804443,  0.02112916,  0.00122372, -0.01288889,
        0.00112562, -0.00924781, -0.0164553 ,  0.01534601])

In [62]:
#to find STD of 'Closing Price'
print('Standard deviation = ',np.std(returns))

Standard deviation =  0.012922134436826306


In [63]:
logreturns = np.diff(np.log(c))

In [64]:
logreturns

array([ 0.00953488,  0.01668775, -0.00205991, -0.00255903,  0.00887039,
        0.01540739,  0.0093908 ,  0.0082988 , -0.01015864,  0.00649435,
        0.00650813,  0.00200256,  0.00893468, -0.01339027, -0.02183875,
       -0.03468287,  0.01177296,  0.00075857,  0.01528161,  0.01440064,
       -0.011103  ,  0.00801225,  0.02090904,  0.00122297, -0.01297267,
        0.00112499, -0.00929083, -0.01659219,  0.01522945])

In [65]:
posretindices = np.where(returns)
print("Indices with +ve returns", posretindices)

Indices with +ve returns (array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28], dtype=int64),)


In [68]:
returns.itemsize


8

In [69]:
#annual Volatality

In [70]:
annual_volatality = np.std(logreturns)/np.mean(logreturns)

In [71]:
annual_volatality = annual_volatality/np.sqrt(1/252)

In [72]:
annual_volatality

129.27478991115132

In [74]:
monthly_volatality = np.std(logreturns)/np.mean(logreturns)


In [75]:
monthly_volatality = monthly_volatality/np.sqrt(1/12)

In [76]:
monthly_volatality

28.210071915112596