#Extracting Features from Text

Bag of Words Model

In [1]:
#Define a courpus with two doucuments

In [2]:
corpus = ['UNC played Duke in BasketBall','Duke lost the basketball game']

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
vectorizer = CountVectorizer()

In [5]:
print(vectorizer.fit_transform(corpus).todense())

[[1 1 0 1 0 1 0 1]
 [1 1 1 0 1 0 1 0]]


In [6]:
print(vectorizer.vocabulary_)

{'unc': 7, 'played': 5, 'duke': 1, 'in': 3, 'basketball': 0, 'lost': 4, 'the': 6, 'game': 2}


In [7]:
#Add one more document to corpus

corpus = ['UNC played Duke in BasketBall','Duke lost the basketball game','I ate sandwich']

In [11]:
counts = (vectorizer.fit_transform(corpus).todense())

In [9]:
vectorizer.vocabulary_

{'unc': 9,
 'played': 6,
 'duke': 2,
 'in': 4,
 'basketball': 1,
 'lost': 5,
 'the': 8,
 'game': 3,
 'ate': 0,
 'sandwich': 7}

In [10]:
#Euclidean distance funmction can be used to calculate the distance between two or more vectors and it will how semantically close the documents are
from sklearn.metrics.pairwise import euclidean_distances



In [12]:
print('Dist between 1st and 2nd doc:',euclidean_distances(counts[0],counts[1]))

Dist between 1st and 2nd doc: [[2.44948974]]


In [13]:
print('Dist between 1st and 3rd doc:',euclidean_distances(counts[0],counts[2]))

Dist between 1st and 3rd doc: [[2.64575131]]


In [14]:
print('Dist between 2nd and 3rd doc:',euclidean_distances(counts[1],counts[2]))

Dist between 2nd and 3rd doc: [[2.64575131]]


Hidemensional vectors with many zero elements are called as sparse vectors

In [15]:
#Startegies for Dimensionality reduction of text features

Startegy 1 - Stop word Filtering

In [16]:
corpus

['UNC played Duke in BasketBall',
 'Duke lost the basketball game',
 'I ate sandwich']

In [17]:
vectorizer = CountVectorizer(stop_words='english')

In [20]:
counts = vectorizer.fit_transform(corpus).todense()

In [19]:
print(vectorizer.vocabulary_)

{'unc': 7, 'played': 5, 'duke': 2, 'basketball': 1, 'lost': 4, 'game': 3, 'ate': 0, 'sandwich': 6}


In [21]:
print('Dist between 1st and 2nd doc:',euclidean_distances(counts[0],counts[1]))

Dist between 1st and 2nd doc: [[2.]]


Stemming and Lemmitization

In [23]:
corpus = ['He ate the Sandwiches','Every Sandwich was eaten by him']

In [24]:
vectorizer = CountVectorizer(binary=True,stop_words='english')

In [25]:
print(vectorizer.fit_transform(corpus).todense())

[[1 0 0 1]
 [0 1 1 0]]


In [26]:
print(vectorizer.vocabulary_)

{'ate': 0, 'sandwiches': 3, 'sandwich': 2, 'eaten': 1}


In [27]:
#Lemmitization in detail

In [28]:
corpus = ['I am gathering ingredients for the sandwich','There are many wizards at the gathering']

In [29]:
import nltk

C:\Users\asm1318\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [ ]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


In [ ]:
from nltk.stem.wordnet import WordNetLemmatizer

In [ ]:
lemmatizer = WordNetLematizer()

In [ ]:
print(lemmatizer.lemmatizer('gathering'),'v')