In [1]:
'''
Agenda:
- Type casting
Negative indexing
     Indexing with a set
     Indexing a dictionary
- Appending data - in set and lists 
- Updating a list
- Deleting a record
- Operators in Python (membership operator, comparision operator ,logical operator)
1.	Using statistics package for statistical functions
2.	Numpy missing values
3.	Character functions
4.	User defined functions
5.	If else conditions
    a.	In class Activity
6.	For loop and while loop
7.	Numpy array -> High level

'''

'\nAgenda:\n- Type casting\nNegative indexing\n     Indexing with a set\n     Indexing a dictionary\n- Appending data - in set and lists \n- Updating a list\n- Deleting a record\n- Operators in Python (membership operator, comparision operator ,logical operator)\n1.\tUsing statistics package for statistical functions\n2.\tNumpy missing values\n3.\tCharacter functions\n4.\tUser defined functions\n5.\tIf else conditions\n    a.\tIn class Activity\n6.\tFor loop and while loop\n7.\tNumpy array -> High level\n\n'

In [1]:
float_num = 4.67
print("Now object its integer:",int(float_num),type(int(float_num)))

Now object its integer: 4 <class 'int'>


In [2]:
# converting to string
print("Now object its String:",str(float_num),type(str(float_num)))

Now object its String: 4.67 <class 'str'>


In [3]:
str_num = '4.67'
# str_num + 1
print(float(str_num) + 1)

5.67


In [4]:
int(float(str_num))

4

In [5]:
# tuple to list
tuple1= 23,"john Smith",101,False
print(tuple1)
print(list(tuple1))

(23, 'john Smith', 101, False)
[23, 'john Smith', 101, False]


In [6]:
list1  = list(tuple1)
print(list1)
list1[0]=26
print(list1)

[23, 'john Smith', 101, False]
[26, 'john Smith', 101, False]


In [7]:
tuple(list1)

(26, 'john Smith', 101, False)

In [8]:
# converting to logical
numbers = 1
print(bool(numbers))
numbers = 0
print(bool(numbers))
numbers = 3
print(bool(numbers))
numbers = -1000
print(bool(numbers))
numbers = None
print(bool(numbers))

True
False
True
True
False


In [9]:
## convert bool to numeric
bool1 = True
print(int(bool1))
bool1 = False
print(int(bool1))

1
0


In [15]:
# Activity - try converting set to list and list/tuple to set

Cars1 = {'Audi','Benz','Porshe'}
Cars1
list(Cars1)
tuple(Cars1)

('Benz', 'Porshe', 'Audi')

In [16]:
### indexing – In Detail
### indexing
AgeOfCust = 34,23,35,64,23,21,34,56
print(AgeOfCust)
print(AgeOfCust[3])
print(AgeOfCust[0:5])
print(AgeOfCust[1:])
print(AgeOfCust[-4]) # 4th element from right
print(AgeOfCust[-4:]) # 4th element onwards from left
print(AgeOfCust[-4:-2]) # #4th last and 3rd last element

(34, 23, 35, 64, 23, 21, 34, 56)
64
(34, 23, 35, 64, 23)
(23, 35, 64, 23, 21, 34, 56)
23
(23, 21, 34, 56)
(23, 21)


In [17]:
print(AgeOfCust[:3])

(34, 23, 35)


In [19]:
B = [[1,2,4],(98,101,100)]
print(type(B[0]))
print(type(B[1]))
print(B[1][2])

<class 'list'>
<class 'tuple'>
100


In [20]:
## can not index set directly
Auto_survey = {'BMW', 'BMW','AUDI','Merc', 'Merc','Bentley','Mini Cooper','Suzuki','Hundai'}
print(Auto_survey)
# below will not work
# Auto_survey[2]
list(Auto_survey)[2]


{'Bentley', 'Merc', 'AUDI', 'Mini Cooper', 'Hundai', 'Suzuki', 'BMW'}


'AUDI'

In [21]:
# indexing dictionary
first_dict = {'John Email ID':"John@abc.com",'kelly':"kelly@org.com",'ids':[101,102]}
print(first_dict)

{'John Email ID': 'John@abc.com', 'kelly': 'kelly@org.com', 'ids': [101, 102]}


In [22]:
# below will not work
# first_dict[0]

In [23]:
print(first_dict['John Email ID'])
print(first_dict['ids'])
print(first_dict['ids'][0])

John@abc.com
[101, 102]
101


In [24]:
first_dict.keys()

dict_keys(['John Email ID', 'kelly', 'ids'])

In [25]:
first_dict.values()

dict_values(['John@abc.com', 'kelly@org.com', [101, 102]])

In [26]:
dir()

['AgeOfCust',
 'Auto_survey',
 'B',
 'Cars1',
 'In',
 'Out',
 '_',
 '_11',
 '_12',
 '_13',
 '_14',
 '_15',
 '_20',
 '_24',
 '_25',
 '_4',
 '_7',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i11',
 '_i12',
 '_i13',
 '_i14',
 '_i15',
 '_i16',
 '_i17',
 '_i18',
 '_i19',
 '_i2',
 '_i20',
 '_i21',
 '_i22',
 '_i23',
 '_i24',
 '_i25',
 '_i26',
 '_i3',
 '_i4',
 '_i5',
 '_i6',
 '_i7',
 '_i8',
 '_i9',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'bool1',
 'exit',
 'first_dict',
 'float_num',
 'get_ipython',
 'list1',
 'numbers',
 'quit',
 'str_num',
 'tuple1']

In [25]:
# delete an object
del(Auto_survey,B)
dir()

['AgeOfCust',
 'In',
 'Out',
 '_',
 '_1',
 '_16',
 '_18',
 '_23',
 '_24',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i11',
 '_i12',
 '_i13',
 '_i14',
 '_i15',
 '_i16',
 '_i17',
 '_i18',
 '_i19',
 '_i2',
 '_i20',
 '_i21',
 '_i22',
 '_i23',
 '_i24',
 '_i25',
 '_i3',
 '_i4',
 '_i5',
 '_i6',
 '_i7',
 '_i8',
 '_i9',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'bool1',
 'exit',
 'first_dict',
 'float_num',
 'get_ipython',
 'list1',
 'numbers',
 'quit',
 'str_num',
 'tuple1']

In [28]:
########### Appending data
# for set
Auto_survey1= set(['BMW', 'BMW','AUDI','Merc', 'Merc','Bentley','Mini Cooper','Suzuki','Hundai'])
Auto_survey2= set(['BMW', 'Renault'])
print(Auto_survey1)
print(Auto_survey2)

{'Hundai', 'Merc', 'Mini Cooper', 'Suzuki', 'BMW', 'AUDI', 'Bentley'}
{'BMW', 'Renault'}


In [31]:
Combined = Auto_survey1 | Auto_survey2
print(Combined)

{'Hundai', 'Merc', 'Mini Cooper', 'Suzuki', 'Renault', 'BMW', 'AUDI', 'Bentley'}


In [29]:
Intersection_cars = Auto_survey1 & Auto_survey2
print(Intersection_cars)

{'BMW'}


In [39]:
Auto_survey1-Auto_survey2

{'AUDI', 'Bentley', 'Hundai', 'Merc', 'Mini Cooper', 'Suzuki'}

In [40]:
Auto_survey2-Auto_survey1

{'Renault'}

In [32]:
#  Appending lists
list1= [6,3,4,5,2]
list2= [6,100,101,107,108,107,100]
list1 + list2

[6, 3, 4, 5, 2, 6, 100, 101, 107, 108, 107, 100]

In [33]:
# for list and tuple
tuple1= (6,3,4,5,2)
list2= [100,101,107,108,107,100]
list(tuple1) + list2

[6, 3, 4, 5, 2, 100, 101, 107, 108, 107, 100]

In [34]:
# for tuples
tuple1= (6,3,4,5,2)
tuple2= (100,101,107,108,107,100)
tuple1 + tuple2

(6, 3, 4, 5, 2, 100, 101, 107, 108, 107, 100)

In [28]:
# update a list
First_list = ['Mark',34,19.6,False]
First_list.append("Jonathan")
print(First_list)

['Mark', 34, 19.6, False, 'Jonathan']


In [29]:
First_list = ['Mark',34,19.6,False]

First_list.insert(1,"Anderson Thompson")
print(First_list)


['Mark', 'Anderson Thompson', 34, 19.6, False]


In [30]:
## deleting a record
First_list = ['Mark',34,19.6,False]
First_list.remove('Mark')
First_list.remove(34)
print(First_list)

[19.6, False]


In [40]:
## deleting a record at a defined index value
First_list = ['Mark',34,19.6,False]
First_list.pop(0)
print(First_list)

[34, 19.6, False]


In [41]:
## repetition
First_list = ['Mark',34,19.6,False]
First_list*3

['Mark', 34, 19.6, False, 'Mark', 34, 19.6, False, 'Mark', 34, 19.6, False]

In [42]:
import pandas as pd
income = pd.Series([2000,2300,4100])
income*1.2

0    2400.0
1    2760.0
2    4920.0
dtype: float64

In [45]:
## + operator for concatenation
FN = "Geroge"
LN = "Washington"
FullName = FN +" " + LN
print(FullName)
print('Customer Name is:',FN + LN)
print('Customer Name is:',FN + " " + LN)

Geroge Washington
Customer Name is: GerogeWashington
Customer Name is: Geroge Washington


In [61]:
# Comparison operator
Cust_income = 2000
Credit_cards = 2
print(Cust_income >= 1000)
print(Credit_cards>4)
print(Credit_cards != 2) # not equal to
print(Credit_cards == 2) # If 2 values are equal or not .similar to R programming


True
False
False
True


In [63]:
# Logical operator
## & (and operator) and | (or operator)
print((2>1) & (3>0)) # both conditions are true
print((2>1) & (3>100)) #1st is true and 2nd is false
print((2>10) & (3>1)) #1st is false and 2nd is true
print((2>15) & (3>10)) #both are false

True
False
False
False


In [64]:
## & (and operator) and | (or operator)
print((2>1) | (3>0)) # both conditions are true
print((2>1) | (3>100)) #1st is true and 2nd is false
print((2>10) | (3>1)) #1st is false and 2nd is true
print((2>15) | (3>10)) #both are false

True
True
True
False


In [50]:
# scenario 1
Cust_income = 2000
Credit_cards = 2
### customer should not have more than 3 cards. Income >1800 per month
(Cust_income>1800) & (Credit_cards<=3)


True

In [51]:

# scenario 2
Cust_income = 1500
Credit_cards = 1
### customer should not have more than 3 cards. Income >1800 per month
(Cust_income >1800) &  (Credit_cards<=3)


False

In [52]:

# scenario 3
Cust_income = 2000
Credit_cards = 5
### customer should not have more than 3 cards. Income >1800 per month
(Cust_income >1800) &  (Credit_cards<=3)


False

In [53]:

# scenario 4
Cust_income = 1000
Credit_cards = 5
### customer should not have more than 3 cards. Income >1800 per month
(Cust_income >1800) & (Credit_cards<=3)


False

In [54]:
## or condition with variables - either of condition to be true
# scenario 1
Cust_income = 2000
Credit_cards = 2
### customer should not have more than 3 cards. Income >1800 per month
(Cust_income>1800) | (Credit_cards<=3)

# scenario 2
Cust_income = 1500
Credit_cards = 1
### customer should not have more than 3 cards. Income >1800 per month
(Cust_income>1800) | (Credit_cards<=3)

# scenario 3
Cust_income = 2000
Credit_cards = 5
### customer should not have more than 3 cards. Income >1800 per month
(Cust_income>1800) | (Credit_cards<=3)

# scenario 4
Cust_income = 1000
Credit_cards = 5
### customer should not have more than 3 cards. Income >1800 per month
(Cust_income>1800) | (Credit_cards<=3)


False

In [62]:
Marks_math = [45,89,56,34,98]
print(Marks_math)
sum(Marks_math)

[45, 89, 56, 34, 98]


322

In [63]:
import statistics
statistics.mean(Marks_math)

64.4

In [64]:
import statistics as st
st.mean(Marks_math)

64.4

In [65]:
from statistics import mean
mean(Marks_math)

64.4

In [66]:
st.stdev(Marks_math)

27.8621607202313

In [68]:
st.pstdev(Marks_math)

24.920674148184673

In [75]:
## numeric functions
Net_operating_income = -2000
abs(Net_operating_income)


2000

In [76]:
Nums = [-5,-9,5,7]
min(Nums)

-9

In [77]:
max(Nums)

7

In [78]:
dir(statistics)

['Decimal',
 'Fraction',
 'StatisticsError',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_coerce',
 '_convert',
 '_counts',
 '_exact_ratio',
 '_fail_neg',
 '_find_lteq',
 '_find_rteq',
 '_isfinite',
 '_ss',
 '_sum',
 'bisect_left',
 'bisect_right',
 'collections',
 'groupby',
 'harmonic_mean',
 'math',
 'mean',
 'median',
 'median_grouped',
 'median_high',
 'median_low',
 'mode',
 'numbers',
 'pstdev',
 'pvariance',
 'stdev',
 'variance']

In [86]:
## character functions
Name="John Anderson"
print(Name.upper())
print(Name.lower())
print(Name.title())

JOHN ANDERSON
john anderson
John Anderson


In [81]:
Cust_names = pd.Series(["John Smith","Lisa Anderson","thomas brooke","Paul"])
print(Cust_names)


0       John Smith
1    Lisa Anderson
2    thomas brooke
3             Paul
dtype: object


In [82]:
print(type(Cust_names))

<class 'pandas.core.series.Series'>


In [83]:
print(Cust_names.dtype)

object


In [89]:
########### if else condition
Age = 18
if Age<18:
    print('Minor')
else:
    print('Major')


Major


In [ ]:
Age = 90
if Age<18:
    print('Minor')
elif Age<50:
    print('Major')
else:
    print('Old')

In [92]:
# nested condition
Age = 50
IQ = "Intelligent"
if Age<18:
    if IQ == "Intelligent":
        print('Minor+Intelligent')
    else:
        print('Minor+Normal')
elif Age<50:
    print('Major')
else:
    print('Old')

Old


In [95]:
# step 1 - creating a function
def Print_month():
    return "The current month is April"


In [96]:

# Step 2 - Executing function
Print_month()


'The current month is April'

In [98]:
## function with 1 parameter
# step 1 - creating a function
def Print_month(ThisMonth):
    return "The current month is: " + ThisMonth

# Step 2 - Executing function
Print_month('April')


'The current month is: April'

In [102]:
## function with > 1 parameter
# step 1 - creating a function
def Print_month(ThisMonth,ThisYear):
    return "The current month is: " + ThisMonth + " and Year is: " + ThisYear


Print_month("April","2020")

'The current month is: April and Year is: 2020'

In [103]:
def Power_fn(x,y):
    return x**y

Power_fn(2,3)

8

In [ ]:
#home work - Make a function that converts sales from euros to dollars considering input is Euro. 1 euro = 1.45 dollar

In [104]:
################ function with if else condition
def check_age(Age):
    if Age<18:
        return 'Minor'
    elif Age<50:
        return 'Major'
    else:
        return 'Old'

check_age(17)


'Minor'

In [ ]:
'''
Activity 
*********
Math_marks = xxx
Science_Marks = xxx
1. For a student to get admitted to "Science" Stream he should get Marks in Math >70 AND marks in science as >75 
Other wise he will be into "Non-Science" stream.
2. Exception - If marks in math or science i.e. either is >90 irrespective of fact the point 1 cut off is met or not student will be 
eligible for Science steam.
Create if else condition WITH USER DEFINED FUNCTION with output as "Science stream Eligible" and "Science stream NOT Eligible"
'''

In [107]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [108]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [109]:
for i in range(10):
    print(i*10)

0
10
20
30
40
50
60
70
80
90


In [110]:
for i in range(10):
    print(i+5)

5
6
7
8
9
10
11
12
13
14


In [111]:
Store_list = ['McDonald','Taco Bell','Dunkin','Wendy','Chipotle']

for Store_name in Store_list:
    print(Store_name)

McDonald
Taco Bell
Dunkin
Wendy
Chipotle


In [114]:
for i in (range(10)):
    print (i)
    if i > 5:
        break

0
1
2
3
4
5
6


In [118]:
list(range(10,50))

[10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49]

In [119]:
list(range(10,50,5))

[10, 15, 20, 25, 30, 35, 40, 45]

In [120]:
# while loop
temp = 90
while temp<95:
    print('Temp Before Incrementing:',temp,'After Incrementing:',(temp+1))
    temp=temp+1 


Temp Before Incrementing: 90 After Incrementing: 91
Temp Before Incrementing: 91 After Incrementing: 92
Temp Before Incrementing: 92 After Incrementing: 93
Temp Before Incrementing: 93 After Incrementing: 94
Temp Before Incrementing: 94 After Incrementing: 95


In [121]:
##################### Lesson 05 #####################
distance = [10,15,23,14]
time =     [.3,.47,.2,.1]
# below will not work
distance/time


TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [129]:
import numpy as np
distance_array = np.array(distance)
print(distance_array)
print(type(distance_array))
distance_array.dtype

[10 15 23 14]
<class 'numpy.ndarray'>


dtype('int64')

In [127]:
time_array = np.array(time)
time_array

array([0.3 , 0.47, 0.2 , 0.1 ])

In [130]:
Speed = distance_array/time_array
Speed

array([ 33.33333333,  31.91489362, 115.        , 140.        ])

In [133]:
Speed.round(2)

array([ 33.33,  31.91, 115.  , 140.  ])

In [131]:
Speed.dtype

dtype('float64')

In [134]:
fl_num =4.6756576
round(fl_num,2)

4.68

In [ ]:
'''
Home work
*********
Math_marks = xxx
Science_Marks = xxx
1. For a student to get admitted to "Science" Stream he should get Marks in Math >70 AND marks in science as >75 
Other wise he will be into "Non-Science" stream.
2. Exception - If marks in math or science i.e. either is >90 irrespective of fact the point 1 cut off is met or not student will be 
eligible for Science steam.
Create if else condition WITH USER DEFINED FUNCTION with output as "Science stream Eligible" and "Science stream NOT Eligible"

'''

In [22]:
Math_Marks = 91
Science_Marks = 92

if(Math_Marks > 70 & Science_Marks > 75):
    print('You are admitted in our school')
elif(Math_Marks > 90):
    print('You are addmitted in our school')
elif(Science_Marks > 90):
    print('You are addmitted in our school')
else:
    print('You are not admiited in our school')

You are addmitted in our school


In [14]:
def currencyconv(Euros):
    return (Euros*1.45)



In [15]:
currencyconv(45)

65.25

In [135]:
 8/2*(2+2) 

16.0