In [10]:
import scipy as sp
import numpy as np

In [11]:
from scipy.integrate import quad


In [3]:
#define a function Integral of x

def integrateFunction(x):
    return x

In [5]:
quad(integrateFunction,0,2)

(2.0, 2.220446049250313e-14)

In [6]:
def integrateFn(x,a,b):
    return x*a+b

In [7]:
a = 3
b = 2

In [8]:
quad(integrateFn,0,1,args=(a,b))

(3.5, 3.885780586188048e-14)

Optimization

In [13]:
#Define a function

def F(x):
    return x**2+5*np.sin(x)
    
    

In [16]:
minimaValue = sp.optimize.minimize(F,x0=2,method='bfgs',options={'disp':True})

Optimization terminated successfully.
         Current function value: -3.246394
         Iterations: 5
         Function evaluations: 27
         Gradient evaluations: 9


In [18]:
minimaValue = sp.optimize.minimize(F,x0=2,method='bfgs')

In [19]:
minimaValue

      fun: -3.2463942726915196
 hess_inv: array([[0.15445831]])
      jac: array([-4.47034836e-07])
  message: 'Optimization terminated successfully.'
     nfev: 27
      nit: 5
     njev: 9
   status: 0
  success: True
        x: array([-1.11051058])

Linear Algebra 

In [27]:
# 1. Finding determinants

Matrix = np.array([[5,4],[7,9]])

In [28]:
Matrix

array([[5, 4],
       [7, 9]])

In [29]:
sp.linalg.det(Matrix)

16.999999999999996

In [31]:
numArray = np.array([[2,3,1],[-1,5,4],[3,2,9]])

In [32]:
numArrRHS = np.array([21,9,6])

In [38]:
x = sp.linalg.solve(numArray,numArrRHS)

In [39]:
x

array([ 4.95,  4.35, -1.95])

In [36]:
np.round(x)

array([ 5.,  4., -2.])

Single Value Decomposition


In [40]:
numSvdarra = np.array([[3,5,1],[2,4,7]])

In [41]:
numSvdarra.shape

(2, 3)

In [42]:
sp.linalg.svd(numSvdarra)

(array([[-0.52059745, -0.85380226],
        [-0.85380226,  0.52059745]]),
 array([9.44041431, 3.85727593]),
 array([[-0.34631921, -0.63749281, -0.68823391],
        [-0.39411541, -0.56688231,  0.72340687],
        [-0.85131431,  0.52177328, -0.0549235 ]]))

Scipy - Eigen Values and Eigen Vectors

In [43]:
test_rating_data = np.array([[5,8],[3,6]])

In [44]:
eigenValues,eigenVectors = sp.linalg.eig(test_rating_data)

In [45]:
eigenValues

array([ 0.5755711+0.j, 10.4244289+0.j])

In [46]:
eigenVectors

array([[-0.87508514, -0.82767485],
       [ 0.483969  , -0.56120793]])

Scipy - Statistics

In [47]:
from scipy.stats import norm

In [48]:
norm.rvs(loc=0,scale=1,size=10 )

array([ 1.22060889,  0.4464854 ,  0.12161717, -1.11773179,  0.79970274,
        0.15201874,  1.36383793,  0.31720339, -0.848819  ,  0.60959608])

In [49]:
norm.cdf(5,loc=1,scale=2)

0.9772498680518208

In [50]:
norm.pdf(9,loc=1,scale=2)

6.691511288244268e-05