In [2]:
import numpy as np

In [3]:
first_numpy_array = np.array([1,2,43,4])

In [4]:
first_numpy_array

array([ 1,  2, 43,  4])

In [5]:
#array with zeros

array_with_zeros = np.zeros([3,3])

In [6]:
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
array_with_zeros.shape

(3, 3)

In [8]:
array_with_zeros.ndim

2

In [9]:
array_with_ones = np.ones([2,2])

In [10]:
array_with_ones

array([[1., 1.],
       [1., 1.]])

In [11]:
#array with Empty

array_with_empty = np.empty([2,3])

In [12]:
array_with_empty

array([[1.3e-322, 0.0e+000, 0.0e+000],
       [0.0e+000, 0.0e+000, 0.0e+000]])

In [13]:
#array with arrange

np_arrange = np.arange(12)

In [14]:
np_arrange #one dimensional Array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
np_arrange.reshape(3,4) #conv to 2 dim array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
#linspace for linearly arranged (space) data elements

np_linspace = np.linspace(1,6,4)  #(start,end,totalno.of equidistant elements)

In [19]:
np_linspace

array([1.        , 2.66666667, 4.33333333, 6.        ])

In [20]:
#three dim array

np_arrange2 = np.arange(27)

In [21]:
np_arrange2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [22]:
np_arrange2.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

Numpy - Basic OPerations

In [23]:
#addition

np.add(45,20)

65

In [24]:
np.subtract(30,50)

-20

In [27]:
np_dialy_wage = np.array([7,8,11,14,12])

In [28]:
np_dialy_wage*15

array([105, 120, 165, 210, 180])

In [29]:
sum(np_dialy_wage*15)

780

COmparision Operator

In [30]:
np_weekly_hrs = np.array([23,41,55,34,24])

In [31]:
Week_with_morethan40hrs = np_weekly_hrs>40

In [32]:
Week_with_morethan40hrs

array([False,  True,  True, False, False])

In [33]:
Week_with_morethan40hrs[np_weekly_hrs>40]

array([ True,  True])

In [34]:
Week_with_morethan40hrs[np_weekly_hrs!=40]

array([False,  True,  True, False, False])

In [36]:
Training_hrs = np.array([8,6,11,13,14])

In [38]:
Training_hrs[Training_hrs>8]

array([11, 13, 14])

In [39]:
Training_hrs[Training_hrs>5]

array([ 8,  6, 11, 13, 14])

In [40]:
Training_hrs[Training_hrs!=11]

array([ 8,  6, 13, 14])

Logical Operations

In [44]:
np.logical_and(Training_hrs>=5,Training_hrs<=11)

array([ True,  True,  True, False, False])

Accessing Array Elements

In [46]:
cyclist_data1 = np.array([10,12,43,23])
cyclist_data2 = np.array([11,34,26,17])

In [48]:
cyclist_2darray = np.array([cyclist_data1,cyclist_data2])

In [49]:
cyclist_2darray

array([[10, 12, 43, 23],
       [11, 34, 26, 17]])

In [51]:
cyclist_2darray[0]

array([10, 12, 43, 23])

In [52]:
cyclist_2darray[1]

array([11, 34, 26, 17])

In [53]:
cyclist_2darray[0][0]

10

In [54]:
cyclist_2darray[:,1:3]

array([[12, 43],
       [34, 26]])

In [55]:
#iterate through each element

for cyclist_2darray_value in cyclist_2darray:
    print(cyclist_2darray_value)

[10 12 43 23]
[11 34 26 17]


In [59]:
test_scores = np.array([[30,45,56,78],[25,54,68,97]])

In [60]:
test_scores.ndim

2

In [61]:
passing_score = test_scores>50

In [62]:
passing_score

array([[False, False,  True,  True],
       [False,  True,  True,  True]])

In [63]:
test_scores[passing_score]

array([56, 78, 54, 68, 97])

Mathematical Functions of Numpy

In [64]:
cyclist_2darray.ravel() #flatten the 2d array into 1d 

array([10, 12, 43, 23, 11, 34, 26, 17])

In [68]:
cyclist_2darray.reshape(2,4)

array([[10, 12, 43, 23],
       [11, 34, 26, 17]])

In [69]:
#broadcasting

array_a = np.array([1,2,5,6,7])
array_b = np.array([3.5,6.8,4.0,2.3,7.8])

In [74]:
array_a.shape == array_b.shape


True

In [75]:
Scalar_val = 3

In [76]:
array_a*Scalar_val

array([ 3,  6, 15, 18, 21])

In [77]:
array_a*array_b

array([ 3.5, 13.6, 20. , 13.8, 54.6])

In [78]:
inverse_array = np.array([[10,12],[15,25]])

In [79]:
np.linalg.inv(inverse_array)

array([[ 0.35714286, -0.17142857],
       [-0.21428571,  0.14285714]])