In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('Recommend.csv')

In [4]:
df

user_id  movie_id  rating  timestamp
0          196       242       3  881250949
1          186       302       3  891717742
2           22       377       1  878887116
3          244        51       2  880606923
4          166       346       1  886397596
...        ...       ...     ...        ...
99995      880       476       3  880175444
99996      716       204       5  879795543
99997      276      1090       1  874795795
99998       13       225       2  882399156
99999       12       203       3  879959583

[100000 rows x 4 columns]

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
#let store the count of User ID unique values in n_users

n_users = df.user_id.unique().shape[0]

In [7]:
n_users

943

In [8]:
#let store the count of Movies unique values in n_movies
n_movies = df.movie_id.unique().shape[0]

In [9]:
n_movies

1682

In [11]:
train_data,test_data = train_test_split(df,test_size=0.25)

In [12]:
#We need to create a matrix which would contain number of users,no. of movies and their corresponding ratings

train_data_matrix = np.zeros((n_users,n_movies))

In [13]:
#Iterate through Training data to record ratings into train_data_matrix

for line in train_data.itertuples():
    #[user_id index, movie_id index] = given rating.
    train_data_matrix[line[1]-1,line[2]-1] = line[3]
    
train_data_matrix

array([[5., 0., 4., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

In [14]:
test_data_matrix = np.zeros((n_users, n_movies))
for line in test_data.itertuples():
    #[user_id index, movie_id index] = given rating.
    test_data_matrix[line[1]-1, line[2]-1] = line[3]
test_data_matrix

array([[0., 3., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [15]:
from sklearn.metrics import pairwise_distances
user_similarity = pairwise_distances(train_data_matrix, metric='cosine')
movie_similarity = pairwise_distances(train_data_matrix.T, metric='cosine')
mean_user_rating = train_data_matrix.mean(axis=1)[:, np.newaxis] 
ratings_diff = (train_data_matrix - mean_user_rating) 
user_pred = mean_user_rating + user_similarity.dot(ratings_diff) / np.array([np.abs(user_similarity).sum(axis=1)]).T
user_pred

array([[ 1.61076191,  0.56263525,  0.48092252, ...,  0.3068345 ,
         0.30667928,  0.30644616],
       [ 1.32355633,  0.25822101,  0.13336062, ..., -0.06565694,
        -0.06418078, -0.06419312],
       [ 1.34926979,  0.21928136,  0.10321333, ..., -0.10305931,
        -0.10120283, -0.10116312],
       ...,
       [ 1.20798846,  0.18420391,  0.06522544, ..., -0.12804367,
        -0.12713347, -0.12711383],
       [ 1.37498662,  0.28553522,  0.19236079, ..., -0.00442547,
        -0.00387361, -0.00342261],
       [ 1.41411683,  0.34528853,  0.27257673, ...,  0.09570022,
         0.09575456,  0.09578558]])